package com.ameren.outage.order.core.enums;

public enum FilterResult {
	FAILED,
	SUCCESS, 
//	CUSTOMER_REPORTED, 
	CUSTOMER_REGISTERED, 
	VOICE_OPERATING_CENTERS_NOT_LOADED, 
	CUSTOMER_VOICE_ELIGIBLE, 
	CUSTOMER_NOT_VOICE_ELIGIBLE, 
	NOT_OK_TO_CALL_BACK, 
	INVALID_PRIMARY_PHONE, 
	OK_INVALID_ALT_PRIMARY_PHONE,
    FAILED_PUBLISH_TO_QUEUE, 
    CUSTOMER_REPORTED_ESRT_NULL, 
    CUSTOMER_REPORTED_ESRT_EXPIRED, 
    CUSTOMER_REPORTED_PPO_TO_ESRT_ELIGIBLE; 
	
	public static boolean isSuccess(FilterResult result) {
		return SUCCESS == result || 
				CUSTOMER_REGISTERED == result || 
				CUSTOMER_VOICE_ELIGIBLE == result || 
				CUSTOMER_REPORTED_PPO_TO_ESRT_ELIGIBLE == result;
	}

}
